# Dockerfile.cyberlab
FROM debian:latest

# Installe tous les outils d'un coup + proprement
RUN apt update && apt install -y \
    curl \
    git \
    wget \
    hashcat \
    nano \
    nmap \
    sqlmap \
    tcpdump \
    netcat-openbsd \
    gobuster \
    whois \
    dnsutils \
    dirb \
    python3-pip \
    openssh-server && \
    echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Crée un utilisateur non-root avec un mot de passe
RUN useradd -m -s /bin/bash dockeruser && \
    usermod --shell /bin/bash dockeruser && \
    echo "dockeruser:changeme" | chpasswd && \
    adduser dockeruser sudo && \
    touch /home/dockeruser/.hushlogin

# Active les logs SSH pour debug (facultatif)
RUN echo "LogLevel VERBOSE" >> /etc/ssh/sshd_config

# Active la bannière SSH
RUN echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config

# Crée un message de bienvenue simple
RUN echo '#!/bin/bash' > /etc/update-motd.d/99-custom && \
    echo 'echo "🐧 Bienvenue sur la VM Debian SSH sécurisée"' >> /etc/update-motd.d/99-custom && \
    echo 'echo "👤 Utilisateur : $(whoami)"' >> /etc/update-motd.d/99-custom && \
    echo 'echo "🕒 Date       : $(date)"' >> /etc/update-motd.d/99-custom && \
    echo 'echo "📡 IP interne : $(hostname -I)"' >> /etc/update-motd.d/99-custom && \
    chmod +x /etc/update-motd.d/99-custom
    

# Sécurise SSH : désactive root + autorise dockeruser
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
    echo 'AllowUsers dockeruser' >> /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Crée le dossier SSH de l'utilisateur
RUN mkdir -p /home/dockeruser/.ssh && \
    chown -R dockeruser:dockeruser /home/dockeruser && \
    chmod 700 /home/dockeruser/.ssh

RUN echo "🐳 Bienvenue sur le Docker CyberLab !" > /etc/issue.net && \
    echo "💀 Usage strictement réservé aux tests de cybersécurité" >> /etc/issue.net && \
    echo "👤 Utilisateur : dockeruser" >> /etc/issue.net && \
    echo "⏰ Date       : \$(date)" >> /etc/issue.net && \
    echo "📍 IP interne : \$(hostname -I)" >> /etc/issue.net
    
# Crée le répertoire nécessaire à sshd
RUN mkdir /var/run/sshd

# Expose le port SSH
EXPOSE 22

# Lance le service SSH
CMD ["/usr/sbin/sshd", "-D"]


